# Example config YAML file
node1:
  class name: Test_Pub
  location: example/nodes/test_pub/test.py
  args:
    number of pings: 10

node2:
  class name: Test_Sub
  location: example/nodes/test_sub/test.py
